#+TITLE: Demeter To Do List (also Athena and Artemis)
#+AUTHOR: Bruce Ravel
#+EMAIL: bravel AT bnl DOT gov
#+TAGS: PDL HUH Advanced Windows

* top of the to do list [0/3]

  1. [ ] Shelly's atoms bug (see mail 17 June 06:35:58 pm)
  2. [ ] Handle CIF import problems more gracefully
  3. [ ] import data into Athena as norm(E)

* things that need doing

** wx issues
  - [ ] why does Wx::FileDialog with ~wxFD_OVERWRITE_PROMPT~ style not work correctly?
        see https://bugzilla.gnome.org/show_bug.cgi?id=631908 and 
        https://bugs.launchpad.net/ubuntu/+source/gtk+2.0/+bug/558674 for more info
        Turns out this is a gtk problem -- I can make the same thing happen with Firefox!

** installation issues [1/1]
  - [X] jpg needs to be a Module::Build ~build_element~, but there are too many such files in the distro .. not all serve a purpose

** Demeter bugs, shortcomings, missing features  [4/19] [21%]
  - [ ] in =Demeter::Data::IO::save_many=, why doesn't updating in n specifying "background" not work to bring data up to date?  (fft, i.e. doing autobk, does work)
  - [ ] +serialize VPath+, put VPath into +dpj and+ fpj files
  - [ ] tie multiple groups together
  - [ ] add a record to an existing Athena project file
  - [ ] set E0 to peak of white line
  - [ ] clnorm + Julia and Jingen's MXAN replacement
  - [ ] Data object should note that datatype is xanes and not compute fbkg since the bkg array does not exist
  - [ ] cannot specify title for stddev and variance plots
  - [ ] Demeter command backend needs lots of polishing
  - [ ] we seem not to have a normalized group (i.e. plot the same as mu or norm)
  - [ ] 3rd derivative
  - [ ] SDK: better documentation for freeze/thaw//serialize/deserialize
  - [ ] error check deserialization for all objects, verify that it is a yaml or whatnot, return 0 if not
  - [ ] per data set R-factors, computed correctly for mkw fits (what is "correctly?")
  - [ ] OpenBabel interface, tied into Feff
  - [X] SDK: "It  seems that if you use the old fashioned GSD string you can have capitals
	in your variable names but if you use the fancy simpleGDS you can not.
  - [X] SDK: something like ~find_path~ method, but which find the path closest to some R value
  - [X] autogenerate workspace for Feff objects (i.e. something in stashdir)
  - [X] better detection of chi ascii data in case of 
        =$data = Demeter::Data->new(file=>"foo.chi");=




** Athena

*** Tools [16/23] [69%]
   - [X] main
   - [X] calibrate
   - [X] align
   - [X] deglitch
   - [ ] /smooth with Savitsky-Golay filter/ [[file:notes/sgolay.m][Matlab routine for SG filter]] 
   - [X] truncate
   - [X] rebin
   - [X] convolution and noise
   - [ ] /deconvolution/
   - [X] self absorption
   - [X] copy series

   - [ ] dispersive
   - [ ] multi-electron removal

   - [X] LCF
   - [ ] /PCA/ [[http://mailman.jach.hawaii.edu/pipermail/perldl/2006-August/000588.html][PCA from PDL mail archives]]
   - [ ] Peak fit
   - [X] log ratio
   - [X] difference

   - [ ] explain FT
   - [X] XDI
   - [X] journal
   - [X] plugins
   - [X] preference 

**** Requires PDL 							:PDL:
    1. smoothing by S-G
    2. deconvolution
    3. PCA

*** needs testing [0/3]
   - [ ] reference of another edge
   - [ ] keV data
   - [ ] importing xmu.dat files into Athena has never been tested

*** needs doing [8/16] [50%]
   - [X] deglitching crashes with gnuplot					:HUH:
   - [X] in project selection dialog, controls for entering a periodic
         subset (i.e. every Nth record starting with the Jth record)
         this would be useful for QXAS or dispersive data files with
         many measurements.  regexp matching against names would also
         be nice
   - [X] replot upon group selection, space is configurable (E, k, R, q, quad, k123, r123, i0/signal, none)
   - [X] column selection dialog is not remembering data numerator and
         denominator selection
   - [X] fix edge step button is not working
   - [X] test preprocessing (I had a crash with all three preproc options selected for data with a reference):
	 ~Can't call method "GetSelection" on an undefined value at /home/bruce/git/demeter/lib/Demeter/UI/Athena/IO.pm line 423.~
   - [X] *Group list* [3/3]
       + [X] reorganize list, keystroke | DnD
       + [X] left click on groups list should post group menu (others?)
       + [X] it needs to be impossible to select nothing in the group list
   - [X] *Pluck buttons* [2/2]
       + [X] implement everywhere needed
       + [X] figure out cause of spurious error on Windows ~failed to get data from the clipboard error -2147221040 openClipboard failed~
   - [ ] implement frozen groups
   - [ ] importing each channel of med data does not work
   - [ ] links to documentation on each tool
   - [ ] *Convolve/noise tool*
       + add noise to chi data
   - [ ] *Difference tool* [0/3]
       + [ ] plot diff for marked groups
       + [ ] plot areas from marked groups
       + [ ] make difference groups from marked groups
   - [-] *LCF tool* [4/5]
       + [X] make data group from fit (use InsertData method)
       + [X] marked groups automation, display in fourth tab, excel output
       + [X] plot in R for fit in k
       + [ ] persistance of LCF results
       + [X] plot sequence results with pgplot
   - [ ] *Plot menu*
       + zoom/unzoom/cursor for pgplot
   - [-] *Help menu* [1/3]
       + [ ] demos
       + [ ] document
       + [X] memory usage

** raw data and plugins
   - Need to expand the filetype system by examining data from *all* the XAS beamlines in the world.  Yes ... all of them.
   - solicit help from the facility representatives

** Windows issues [10/17] [58%] 					    :Windows:
  - [X] parameter group context menus don't get posted (see http://www.nntp.perl.org/group/perl.wxperl.users/2011/03/msg7929.html)
  - [X] ugly background colors on command and status buffer frames (particularly at bottom, also a problem in Artemis)
  - [X] raised text with data name in data frame
  - [X] InitialPage in path list does not get hidden properly
  - [X] colors missing in log file text
  - [X] log frame not displayed/refreshed properly after a fit
  - [X] Artemis key accelerators
  - [X] +spurious message from clipboard+ (worked around)
  - [ ] the frickin' Gnuplot error logs seem to remain open and locked on Windows when a crash happens
  - [ ] status bar does not get color for wait or error messages /this may be unfixable, see/ http://www.nntp.perl.org/group/perl.wxperl.users/2011/04/msg7943.html
  - [X] ifeffit is currently compiled not knowing where to find the feff tables, so PC transforms are not possible.
	in general, the compilation of Ifeffit needs to be better integrated into Strawberry.
  - [ ] The atoms panel background color is too light.  Which window needs its BackgroundColour set to wxNullColour?
  - [ ] clampbox does not get enabled/disabled explicitly, is this another aspect of StaticBox that is different on Windows? (see link above)
  - [ ] fpj file on Win seems to not get unpacked correctly /is this true?/	:Project:
  - [X] Get .prj file to open with a double click into Athena, .fpj into Artemis
  - [ ] relocation of Strawberry leaves Ifeffit unable to find pahse shift and CL tables (use an ENV variable?)
  - [ ] need a script for rewriting .bat files to redirect spew to log files.  this should run after installation as .bat's get overwritten


** Artemis
*** Artemis bugs and missing features [11/17]  [64%]
   - [X] use text buffers as in Athena for TextEntryDialogs
   - [X] import an FPath from a yaml or from a project file, pathlist start page link for doing so
   - [X] should I clear out unfitted fit folders from project upon import?
   - [X] update pods for ~Demeter::Feff::Histogram~ and ~Demeter::Feff::DL_POLY~
   - [X] Rename VPaths in VPath right click menu
   - [X] sending Ifeffit feedback to the buffer makes it unavailable for other purposes.  the big problem
	 is that correlations don't get written to the log file in Artemis (or in a script with =set_mode(screen=>1)=,
	 for that matter...)
   - [X] fit history plotting tool is broken -- it seems that previous fits are not saved, instead current fit is plotted repeatedly
   - [X] fit numbering is wrong, should not increment if previous fit has fitted=0
   - [X] feff does not get a sensible name when opening an empty feff frame
   - [X] what is the purpose of regenerate in fit deserialization?  in any case, need to fix group values *inside* yaml files
   - [ ] *rename Atoms/Feff*
   - [ ] Reorganize lists, move individual items up and down, move blocks up and down, Path list, +Plot list+
   - [ ] discarding last page and returning to initial page has an undefined value problem   :HUH:
   - [ ] status messages in Atoms/Feff frame do not get posted in Artemis status buffer
   - [ ] do SSPaths get serialized and deserialized with the pointers
         to the feff calculation set correctly and no additional
         folders being created in stash (as was the case for FSPath)?
   - [X] pluck buttons have not been implemented
   - [ ] per-data set R-factor reporting in log file is turned off.  see fit_parameter_report in Demeter::Data::I0

**** Project [0/2]
   - [ ] VPaths to/from project file
   - [ ] Indicators to/from project file

**** Advanced fitting						   :Advanced:
***** MFC [0/1]
   - [ ] Balance interstitial energies for MFC fits
***** MDS & Fit Sequence [0/3]
   - [ ] Import mutiple data sets from an Athena project file
   - [ ] feffit.inp import: needs testing; MDS that is not merely MKW
   - [ ] Clone data sets such that the path list gets replicated efficiently (i.e. for MDS fits)


*** Histograms [10/11] [90%]
   - [X] sum histogram bins into a single chi(k) file
   - [X] convert chi(k) data to a mock feffNNNN.dat file
   - [X] Triangle object
     - yields a DS path and a TS path
     - by R and theta
     - +by a trio of Cartesian coordinates+
   - [X] bin nealy colinear configurations by R and theta and sum into a single chi(k)
   - [X] turn SS histogram into a rattle TS histogram
   - [X] three-body histogram from X -- [+] -- X configurations
   - [X] error check numbers before making histograms in Artemis.  it is possible to have value like "3.3."
   - [X] ipot=1 is hardwired in many places -- generalize.... /fixed for SS, same should work for NCL and Thru/
   - [X] scatter plot of ncl distribution
   - [X] factor out DLPOLY dependence into a role so that other MD packages can be added more easily
   - [ ] *Error checking*, e.g. check that there is at least one bin in the supplied range(s)

** Hephaestus [1/1]
  - [X] need to open prefs with root in place so they display correctly on windows as well

** Other object types [0/3]
  - [ ] Structural Units
      + Extension of VPath.  
      + Store GDS, feff, and path objects in a zip file.
      + On import, mark GDS parameters as merge if in conflict
  - [ ] MSPaths
      + Much like SSPath, make an arbitrary n-legged path
  - [ ] Nearly collinear paths
      + Define a three body configuration, generate its 4-legged path and a sequence of three-legged paths along with a mixing parameter.
      + It will take a single set of path parameters that are pushed onto the generated Path objects, except for the amplitude, which will be computed from the mixing parameter.
      + This is a single object for the user to interact with which expands into 2 or 3 3-legged paths and a single 4-legged path



** Windows							    :Windows:
*** DONE non-ascii symbols
*** DONE Fix [[file:lib/Demeter/UI/Wx/CheckListBook.pm][CheckListBook]]
      The solution is shown at the end of Athena.pm.  Define new methods for
      CheckBoxList which maintain an indexed list of groups rather than relying
      upon client data, which simply doesn't work on Windows.

 
* Atoms and Feff

** Atoms [0/5] [0%]
  - [ ] CIF issue: CIF file with "_eof" token at end of file, as in [[file:notes/H16PW12O46.cif][this cif file]]
  - [ ] 2 sites at the same position with occupancies <1.  see file above for an example
  - [ ] George Sterbinsky's recent mailing list post that turned out to be about 
	atoms' sphere and rhomboid in a non-orthogonal group
  - [ ] CIF errors are not handled gracefully (e.g. multiple occupancy)
  - [ ] Rhombic groups seem not be handled properly.  This example fails to generate a subshell of 3 atoms at ~1.9A
         : title name:     Fe2O3  hematite
         : space  R -3 c
         : a    = 5.0380	b    = 5.0380	c    = 13.7720
         : rmax = 6.00	core = Fe1
         : atom
         :   Fe     0.00000   0.00000   0.35530  Fe1
         :   O      0.30590   0.00000   0.25000  O1


** Feff8 is unsupported except as an Atoms output type



* Weird stuff I'd prefer not to implement unless demanded
 1. xfit output (only used by women who glow and men who plunder)
 2. csv and text report (excel *is* implemented)
 3. point finder (this was Shelly's request)
 4. session defaults (did anyone but me actually use these?)
 5. set to standard (i.e. the one that is marked) -- confusing and
    little used
 6. tie relative energy value to changes in E0 (this was something
    Jeremy requested originally)
 7. set e0 by algorithm for all and marked -- also confusing and
    little used
 8. plot margin lines for deglitching, deglitch many points (this was
    something that was most useful for a timing problem at 10ID that
    no longer exists)
 9. preprocessing truncation and deglitching (truncation might be
    worth implementing)

