#!/bin/sh

TOP=../../..
LIB=$TOP/lib
BIN=$TOP/bin
cp $BIN/denv        $BIN/denv.pl
cp $BIN/dhephaestus $BIN/dhephaestus.pl
pod2projdocs -l $LIB \
             -l $BIN \
             -o pods \
             -t Demeter \
             -d "Perl tools for X-ray Absorption Spectroscopy" 1
rm $BIN/denv.pl $BIN/dhephaestus.pl

 
#              -l ../../libperlxray/Absorption/lib \
#              -l ../../libperlxray/Absorption/server \
#              -l ../../libperlxray/Formula/lib \
#              -l ../../libperlxray/Scattering/lib \
#              -l ../../libperlxray/Ifeffit/lib \
