#!/bin/sh

cp ../install_prereqs ../bin/install_prereqs.pl
cp ../bin/denv        ../bin/denv.pl
cp ../bin/hephaestus  ../bin/hephaestus.pl
pod2projdocs -l ../lib \
             -l ../bin \
             -l ../../libperlxray/Absorption/lib \
             -l ../../libperlxray/Absorption/server \
             -l ../../libperlxray/Formula/lib \
             -l ../../libperlxray/Scattering/lib \
             -l ../../libperlxray/SpaceGroup/lib \
             -l ../../libperlxray/Ifeffit/lib \
             -o html \
             -t Demeter \
             -d "Perl tools for X-ray Absorption Spectroscopy" 1
rm ../bin/install_prereqs.pl ../bin/denv.pl ../bin/hephaestus.pl
