
* getting started

installed perl 5.18.1 via perlbrew

~perl Build.pl~ immediately fails for missing File::Copy::Recursive,
which is used in DemeterBuilder.pm

Clarified use of F::C::R in build scripts.  It is now identified as a
build requirement.  It'll get installed at ~./Build installdeps~ time
so that it can be used at ~./Build~ time.

* Build installdeps

this proceeds.

wait a while....

** XMLRPC::Lite

~XMLRPC::Lite~ fails to install.  forcing an install seems to work.
Do one of these:

  : cpanp i --force XMLRPC::Lite

or

  : ~> cpan
  : cpan> force install XMLRPC::Lite

or

  : cpanm -f XMLRPC::Lite

** Crypt::SSLeay

~Crypt::SSLeay~ is a toughie to build.  It was easier to use apt-get
to install ~libcrypt-ssleay-perl~.  Ubuntu 13.04 is at 0.58 on that
library, well behind CPAN's 0.64.  But that's OK.

This gets pulled in with Net::SSLeay, which gets pulled in with
~XMLRPC::Lite~, which is essential to using Larch.  So I'm stuck with
it.

* when switching perl versions with perlbrew

 :  Build touch_wrapper

then

 :  cp /home/bruce/git/demeter/blib/arch/auto/Ifeffit/Ifeffit.so /home/bruce/perl/auto/Ifeffit/Ifeffit.so

